name: Python CI (pytest)

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: |
          pwd
          ls
          echo "----"
          ls -la
          echo "----"
          find . -maxdepth 3 -type d

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd "HW3- CSC310"
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd "HW3- CSC310"
          python -m pytest